"""Solar angle calculation library for solar panel tracking systems."""

from ._types import (
    DayData,
    DualAxisAngles,
    DualAxisEntry,
    LookupTable,
    LookupTableConfig,
    Season,
    SingleAxisEntry,
    SolarPosition,
    SunriseSunset,
    TableMetadata,
)
from .angles import (
    DEGREES_PER_HOUR,
    EARTH_AXIAL_TILT,
    day_of_year,
    deg_to_rad,
    dual_axis_angles,
    equation_of_time,
    example_calculation,
    hour_angle,
    intermediate_angle_b,
    local_solar_time,
    normalize_angle,
    optimal_fixed_tilt,
    rad_to_deg,
    seasonal_tilt_adjustment,
    single_axis_tilt,
    solar_altitude,
    solar_azimuth,
    solar_declination,
    solar_position,
    solar_zenith_angle,
)
from .lookup_table import (
    DEFAULT_CONFIG,
    doy_to_month_day,
    estimate_sunrise_sunset,
    generate_dual_axis_table,
    generate_single_axis_table,
    interpolate_angle,
    intervals_per_day,
    lookup_dual_axis,
    lookup_single_axis,
    minutes_to_time,
    table_to_compact,
    time_to_minutes,
)

__all__ = [
    # Types
    "DayData",
    "DualAxisAngles",
    "DualAxisEntry",
    "LookupTable",
    "LookupTableConfig",
    "Season",
    "SingleAxisEntry",
    "SolarPosition",
    "SunriseSunset",
    "TableMetadata",
    # Constants
    "DEGREES_PER_HOUR",
    "EARTH_AXIAL_TILT",
    "DEFAULT_CONFIG",
    # Angles
    "day_of_year",
    "deg_to_rad",
    "dual_axis_angles",
    "equation_of_time",
    "example_calculation",
    "hour_angle",
    "intermediate_angle_b",
    "local_solar_time",
    "normalize_angle",
    "optimal_fixed_tilt",
    "rad_to_deg",
    "seasonal_tilt_adjustment",
    "single_axis_tilt",
    "solar_altitude",
    "solar_azimuth",
    "solar_declination",
    "solar_position",
    "solar_zenith_angle",
    # Lookup table
    "doy_to_month_day",
    "estimate_sunrise_sunset",
    "generate_dual_axis_table",
    "generate_single_axis_table",
    "interpolate_angle",
    "intervals_per_day",
    "lookup_dual_axis",
    "lookup_single_axis",
    "minutes_to_time",
    "table_to_compact",
    "time_to_minutes",
]
